/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Application {
  'status' : ApplicationStatus,
  'applicant' : Principal,
  'jobId' : bigint,
  'coverLetter' : string,
}
export type ApplicationStatus = { 'interviewed' : null } |
  { 'pending' : null } |
  { 'rejected' : null } |
  { 'shortlisted' : null };
export interface AttendanceLog {
  'logId' : bigint,
  'staffId' : string,
  'staffName' : string,
  'clockIn' : bigint,
  'clockOut' : [] | [bigint],
  'date' : string,
}
export interface DirectApplication {
  'status' : ApplicationStatus,
  'appliedAt' : bigint,
  'email' : string,
  'jobTitle' : string,
  'candidateName' : string,
  'phone' : string,
}
export interface Job {
  'title' : string,
  'salary' : number,
  'createdBy' : Principal,
  'description' : string,
  'requirements' : string,
  'location' : string,
}
export interface StaffAccountInfo {
  'userId' : string,
  'name' : string,
  'isActive' : boolean,
}
export interface StaffLoginResult {
  'userId' : string,
  'name' : string,
}
export interface UserProfile {
  'name' : string,
  'email' : string,
  'details' : string,
  'profileType' : { 'staff' : null } |
    { 'employer' : null } |
    { 'candidate' : null },
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'applyForJob' : ActorMethod<[bigint, string], bigint>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'assignStaffRole' : ActorMethod<[Principal], undefined>,
  'claimAdminSeed' : ActorMethod<[string], boolean>,
  'clockIn' : ActorMethod<[string, string, string], bigint>,
  'clockOut' : ActorMethod<[string], boolean>,
  'createJob' : ActorMethod<[string, string, string, number, string], bigint>,
  'createStaffAccount' : ActorMethod<[string, string, string], boolean>,
  'deactivateStaffAccount' : ActorMethod<[string, boolean], undefined>,
  'deleteJob' : ActorMethod<[bigint], undefined>,
  'deleteStaffAccount' : ActorMethod<[string], undefined>,
  'getApplication' : ActorMethod<[bigint], [] | [Application]>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getJob' : ActorMethod<[bigint], [] | [Job]>,
  'getStaffAttendance' : ActorMethod<[string], Array<AttendanceLog>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'isStaffClockedIn' : ActorMethod<[string], boolean>,
  'isUserStaff' : ActorMethod<[Principal], boolean>,
  'listAllApplications' : ActorMethod<[], Array<[bigint, Application]>>,
  'listAllAttendanceLogs' : ActorMethod<[], Array<AttendanceLog>>,
  'listAllDirectApplications' : ActorMethod<
    [],
    Array<[bigint, DirectApplication]>
  >,
  'listAllUsers' : ActorMethod<[], Array<[Principal, UserProfile]>>,
  'listApplicationsForJob' : ActorMethod<
    [bigint],
    Array<[bigint, Application]>
  >,
  'listJobs' : ActorMethod<[], Array<[bigint, Job]>>,
  'listMyApplications' : ActorMethod<[], Array<[bigint, Application]>>,
  'listStaffAccounts' : ActorMethod<[], Array<StaffAccountInfo>>,
  'removeStaffRole' : ActorMethod<[Principal], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'submitDirectApplication' : ActorMethod<
    [string, string, string, string],
    bigint
  >,
  'updateApplicationStatus' : ActorMethod<
    [bigint, ApplicationStatus],
    undefined
  >,
  'updateDirectApplicationStatus' : ActorMethod<
    [bigint, ApplicationStatus],
    undefined
  >,
  'verifyStaffLogin' : ActorMethod<[string, string], [] | [StaffLoginResult]>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];