/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Application {
  'applicant' : Principal,
  'jobId' : bigint,
  'coverLetter' : string,
}
export interface Job {
  'title' : string,
  'salary' : number,
  'createdBy' : Principal,
  'description' : string,
  'requirements' : string,
  'location' : string,
}
export interface UserProfile {
  'name' : string,
  'email' : string,
  'details' : string,
  'profileType' : { 'employer' : null } |
    { 'candidate' : null },
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'applyForJob' : ActorMethod<[bigint, string], bigint>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createJob' : ActorMethod<[string, string, string, number, string], bigint>,
  'deleteJob' : ActorMethod<[bigint], undefined>,
  'getApplication' : ActorMethod<[bigint], [] | [Application]>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getJob' : ActorMethod<[bigint], [] | [Job]>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'listApplicationsForJob' : ActorMethod<
    [bigint],
    Array<[bigint, Application]>
  >,
  'listJobs' : ActorMethod<[], Array<[bigint, Job]>>,
  'listMyApplications' : ActorMethod<[], Array<[bigint, Application]>>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];