/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const ApplicationStatus = IDL.Variant({
  'interviewed' : IDL.Null,
  'pending' : IDL.Null,
  'rejected' : IDL.Null,
  'shortlisted' : IDL.Null,
});
export const Application = IDL.Record({
  'status' : ApplicationStatus,
  'applicant' : IDL.Principal,
  'jobId' : IDL.Nat,
  'coverLetter' : IDL.Text,
});
export const AttendanceLog = IDL.Record({
  'logId' : IDL.Nat,
  'staffId' : IDL.Text,
  'staffName' : IDL.Text,
  'clockIn' : IDL.Int,
  'clockOut' : IDL.Opt(IDL.Int),
  'date' : IDL.Text,
});
export const UserProfile = IDL.Record({
  'name' : IDL.Text,
  'email' : IDL.Text,
  'details' : IDL.Text,
  'profileType' : IDL.Variant({
    'staff' : IDL.Null,
    'employer' : IDL.Null,
    'candidate' : IDL.Null,
  }),
});
export const Job = IDL.Record({
  'title' : IDL.Text,
  'salary' : IDL.Float64,
  'createdBy' : IDL.Principal,
  'description' : IDL.Text,
  'requirements' : IDL.Text,
  'location' : IDL.Text,
});
export const DirectApplication = IDL.Record({
  'status' : ApplicationStatus,
  'appliedAt' : IDL.Int,
  'email' : IDL.Text,
  'jobTitle' : IDL.Text,
  'candidateName' : IDL.Text,
  'phone' : IDL.Text,
});
export const StaffAccountInfo = IDL.Record({
  'userId' : IDL.Text,
  'name' : IDL.Text,
  'isActive' : IDL.Bool,
});
export const StaffLoginResult = IDL.Record({
  'userId' : IDL.Text,
  'name' : IDL.Text,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'applyForJob' : IDL.Func([IDL.Nat, IDL.Text], [IDL.Nat], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'assignStaffRole' : IDL.Func([IDL.Principal], [], []),
  'claimAdminSeed' : IDL.Func([IDL.Text], [IDL.Bool], []),
  'clockIn' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [IDL.Nat], []),
  'clockOut' : IDL.Func([IDL.Text], [IDL.Bool], []),
  'createJob' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Float64, IDL.Text],
      [IDL.Nat],
      [],
    ),
  'createStaffAccount' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [IDL.Bool], []),
  'deactivateStaffAccount' : IDL.Func([IDL.Text, IDL.Bool], [], []),
  'deleteJob' : IDL.Func([IDL.Nat], [], []),
  'deleteStaffAccount' : IDL.Func([IDL.Text], [], []),
  'getApplication' : IDL.Func([IDL.Nat], [IDL.Opt(Application)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getJob' : IDL.Func([IDL.Nat], [IDL.Opt(Job)], ['query']),
  'getStaffAttendance' : IDL.Func([IDL.Text], [IDL.Vec(AttendanceLog)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'isStaffClockedIn' : IDL.Func([IDL.Text], [IDL.Bool], ['query']),
  'isUserStaff' : IDL.Func([IDL.Principal], [IDL.Bool], ['query']),
  'listAllApplications' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Nat, Application))],
      ['query'],
    ),
  'listAllAttendanceLogs' : IDL.Func([],  [IDL.Vec(AttendanceLog)], ['query']),
  'listAllDirectApplications' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Nat, DirectApplication))],
      ['query'],
    ),
  'listAllUsers' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Principal, UserProfile))],
      ['query'],
    ),
  'listApplicationsForJob' : IDL.Func(
      [IDL.Nat],
      [IDL.Vec(IDL.Tuple(IDL.Nat, Application))],
      ['query'],
    ),
  'listJobs' : IDL.Func([], [IDL.Vec(IDL.Tuple(IDL.Nat, Job))], ['query']),
  'listMyApplications' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Nat, Application))],
      ['query'],
    ),
  'listStaffAccounts' : IDL.Func([], [IDL.Vec(StaffAccountInfo)], ['query']),
  'removeStaffRole' : IDL.Func([IDL.Principal], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'submitDirectApplication' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [IDL.Nat],
      [],
    ),
  'updateApplicationStatus' : IDL.Func([IDL.Nat, ApplicationStatus], [], []),
  'updateDirectApplicationStatus' : IDL.Func(
      [IDL.Nat, ApplicationStatus],
      [],
      [],
    ),
  'listDirectApplicationsWithCredentials' : IDL.Func(
      [IDL.Text, IDL.Text],
      [IDL.Opt(IDL.Vec(IDL.Tuple(IDL.Nat, DirectApplication)))],
      ['query'],
    ),
  'updateDirectApplicationStatusWithCredentials' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Nat, ApplicationStatus],
      [IDL.Bool],
      [],
    ),
  'verifyStaffLogin' : IDL.Func([IDL.Text, IDL.Text], [IDL.Opt(StaffLoginResult)], ['query']),
    'requestPasswordResetOTP' : IDL.Func([IDL.Text], [IDL.Bool], []),
    'verifyOTPAndResetPassword' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [IDL.Bool], []),
    'listPendingOTPs' : IDL.Func([], [IDL.Vec(IDL.Record({'userId': IDL.Text, 'otp': IDL.Text}))], ['query']),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const ApplicationStatus = IDL.Variant({
    'interviewed' : IDL.Null,
    'pending' : IDL.Null,
    'rejected' : IDL.Null,
    'shortlisted' : IDL.Null,
  });
  const Application = IDL.Record({
    'status' : ApplicationStatus,
    'applicant' : IDL.Principal,
    'jobId' : IDL.Nat,
    'coverLetter' : IDL.Text,
  });
  const AttendanceLog = IDL.Record({
    'logId' : IDL.Nat,
    'staffId' : IDL.Text,
    'staffName' : IDL.Text,
    'clockIn' : IDL.Int,
    'clockOut' : IDL.Opt(IDL.Int),
    'date' : IDL.Text,
  });
  const UserProfile = IDL.Record({
    'name' : IDL.Text,
    'email' : IDL.Text,
    'details' : IDL.Text,
    'profileType' : IDL.Variant({
      'staff' : IDL.Null,
      'employer' : IDL.Null,
      'candidate' : IDL.Null,
    }),
  });
  const Job = IDL.Record({
    'title' : IDL.Text,
    'salary' : IDL.Float64,
    'createdBy' : IDL.Principal,
    'description' : IDL.Text,
    'requirements' : IDL.Text,
    'location' : IDL.Text,
  });
  const DirectApplication = IDL.Record({
    'status' : ApplicationStatus,
    'appliedAt' : IDL.Int,
    'email' : IDL.Text,
    'jobTitle' : IDL.Text,
    'candidateName' : IDL.Text,
    'phone' : IDL.Text,
  });
  const StaffAccountInfo = IDL.Record({
    'userId' : IDL.Text,
    'name' : IDL.Text,
    'isActive' : IDL.Bool,
  });
  const StaffLoginResult = IDL.Record({
    'userId' : IDL.Text,
    'name' : IDL.Text,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'applyForJob' : IDL.Func([IDL.Nat, IDL.Text], [IDL.Nat], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'assignStaffRole' : IDL.Func([IDL.Principal], [], []),
    'claimAdminSeed' : IDL.Func([IDL.Text], [IDL.Bool], []),
    'clockIn' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [IDL.Nat], []),
    'clockOut' : IDL.Func([IDL.Text], [IDL.Bool], []),
    'createJob' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Float64, IDL.Text],
        [IDL.Nat],
        [],
      ),
    'createStaffAccount' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [IDL.Bool], []),
    'deactivateStaffAccount' : IDL.Func([IDL.Text, IDL.Bool], [], []),
    'deleteJob' : IDL.Func([IDL.Nat], [], []),
    'deleteStaffAccount' : IDL.Func([IDL.Text], [], []),
    'getApplication' : IDL.Func([IDL.Nat], [IDL.Opt(Application)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getJob' : IDL.Func([IDL.Nat], [IDL.Opt(Job)], ['query']),
    'getStaffAttendance' : IDL.Func([IDL.Text], [IDL.Vec(AttendanceLog)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'isStaffClockedIn' : IDL.Func([IDL.Text], [IDL.Bool], ['query']),
    'isUserStaff' : IDL.Func([IDL.Principal], [IDL.Bool], ['query']),
    'listAllApplications' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Nat, Application))],
        ['query'],
      ),
    'listAllAttendanceLogs' : IDL.Func([], [IDL.Vec(AttendanceLog)], ['query']),
    'listAllDirectApplications' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Nat, DirectApplication))],
        ['query'],
      ),
    'listAllUsers' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Principal, UserProfile))],
        ['query'],
      ),
    'listApplicationsForJob' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(IDL.Tuple(IDL.Nat, Application))],
        ['query'],
      ),
    'listJobs' : IDL.Func([], [IDL.Vec(IDL.Tuple(IDL.Nat, Job))], ['query']),
    'listMyApplications' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Nat, Application))],
        ['query'],
      ),
    'listStaffAccounts' : IDL.Func([], [IDL.Vec(StaffAccountInfo)], ['query']),
    'removeStaffRole' : IDL.Func([IDL.Principal], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'submitDirectApplication' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [IDL.Nat],
        [],
      ),
    'updateApplicationStatus' : IDL.Func([IDL.Nat, ApplicationStatus], [], []),
    'updateDirectApplicationStatus' : IDL.Func(
        [IDL.Nat, ApplicationStatus],
        [],
        [],
      ),
    'listDirectApplicationsWithCredentials' : IDL.Func(
        [IDL.Text, IDL.Text],
        [IDL.Opt(IDL.Vec(IDL.Tuple(IDL.Nat, DirectApplication)))],
        ['query'],
      ),
    'updateDirectApplicationStatusWithCredentials' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Nat, ApplicationStatus],
        [IDL.Bool],
        [],
      ),
    'verifyStaffLogin' : IDL.Func([IDL.Text, IDL.Text], [IDL.Opt(StaffLoginResult)], ['query']),
    'requestPasswordResetOTP' : IDL.Func([IDL.Text], [IDL.Bool], []),
    'verifyOTPAndResetPassword' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [IDL.Bool], []),
    'listPendingOTPs' : IDL.Func([], [IDL.Vec(IDL.Record({'userId': IDL.Text, 'otp': IDL.Text}))], ['query']),
  });
};

export const init = ({ IDL }) => { return []; };